version: "3"

volumes:
  mongodb_volume:

services:
  partner:
    container_name: partner-service
    build: ./partner
    restart: always
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/service
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    links:
      - mongodb

  rate:
    container_name: rate-service
    build: ./rate
    restart: always
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/service
    ports:
      - "8081:8080"
    depends_on:
      - mongodb
    links:
      - mongodb

  limit:
    container_name: limit-service
    build: ./limit
    restart: always
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/service
    ports:
      - "8082:8080"
    depends_on:
      - mongodb
    links:
      - mongodb

  mongodb:
    image: 'mongo'
    restart: always
    volumes:
      - mongodb_volume:/data/db
    ports:
      - "27017:27017"